CREATE TABLE NHACUNGCAP (
	MACONGTY nvarchar(10)   NOT NULL PRIMARY KEY ,
	TENCONGTY nvarchar(40)   NOT NULL  ,
	TENGIAODICH nvarchar(30) ,
	DIACHI nvarchar(50) ,
	DIENTHOAI nvarchar(15) ,
	FAX nvarchar(15),
	EMAIL nvarchar(30) 
);
CREATE TABLE LOAIHANG (
	MALOAIHANG nvarchar(10)  NOT NULL PRIMARY KEY ,
	TENLOAIHANG nvarchar(40)   NOT NULL  
);
CREATE TABLE MATHANG (
	MAHANG nvarchar(10)  NOT NULL PRIMARY KEY ,
	TENHANG nvarchar(50)   NOT NULL ,
	MACONGTY nvarchar(10)   NOT NULL  ,
	MALOAIHANG nvarchar(10)   NOT NULL  ,
	SOLUONG INT ,
	DONVITINH nvarchar(10),
	GIAHANG int,
	CONSTRAINT FK_MACONGTY FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
	CONSTRAINT FK_MALOAIHANG FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
);
CREATE  TABLE NHANVIEN (
	MANHANVIEN nvarchar(10) NOT NULL PRIMARY KEY ,
	HO nvarchar(20) NOT NULL  ,
	TEN nvarchar(10) NOT NULL  ,
	NGAYSINH DATETIME  ,
	NGAYLAMVIEC DATETIME  ,
	DIACHI nvarchar(50)  ,
	DIENTHOAI nvarchar(50)  ,
	LUONGCOBAN int,
	PHUCAP int
);
CREATE  TABLE KHACHHANG (
	MAKHACHHANG nvarchar(10) NOT NULL PRIMARY KEY ,
	TENCONGTY nvarchar(40) NOT NULL  ,
	TENGIAODICH nvarchar(30) ,
	DIACHI nvarchar(50) ,
	DIENTHOAI nvarchar(15) ,
	FAX nvarchar(15),
	EMAIL nvarchar(30) 
);
CREATE  TABLE DONDATHANG (
	SOHOADON  int NOT NULL PRIMARY KEY ,
	MAKHACHHANG nvarchar(10) NOT NULL  ,
	MANHANVIEN nvarchar(10) ,
	NGAYDATHANG  DATETIME,
	NGAYGIAOHANG DATETIME ,
	NGAYCHUYENHANG DATETIME,
	NOIGIAOHANG nvarchar(50) ,
	CONSTRAINT FK_MAKHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
	CONSTRAINT FK_MANHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
);
CREATE  TABLE CHITIETDATHANG (
	SOHOADON  int NOT NULL ,
	MAHANG nvarchar(10) NOT NULL  ,
	MANHANVIEN nvarchar(10) ,
	GIABAN int ,
	SOLUONG smallint ,
	MUCGIAMGIA numeric(2,1),
	PRIMARY KEY (SOHOADON,MAHANG)
);
/* Bổ sung ràng buộc thiết lập giá trị mặc định bằng 1 cho cột SOLUONG và bằng 0
cho cột MUCGIAMGIA trong bảng CHITIETDATHANG .*/
ALTER TABLE CHITIETDATHANG ADD CONSTRAINT SOLUONG DEFAULT 1 FOR SOLUONG ;
ALTER TABLE CHITIETDATHANG ADD DEFAULT(0) FOR MUCGIAMGIA 

/*
 * Bổ sung cho bảng DONDATHANG ràng buộc kiểm tra ngày giao hàng và ngày
chuyển hàng phải sau hoặc bằng với ngày đặt hàng
 */
ALTER TABLE DONDATHANG ADD CONSTRAINT CHK_NGAYGIAOHANG CHECK (NGAYDATHANG >= NGAYGIAOHANG AND NGAYDATHANG >= NGAYCHUYENHANG);

/*
 * 4. Bổ sung ràng buộc cho bảng NHANVIEN để đảm bảo rằng một nhân viên chỉ có thể
làm việc trong công ty khi đủ 18 tuổi và không quá 60 tuổi. */


/*
 * 1. Cho biết danh sách các đối tác cung cấp hàng cho công ty. */
SELECT * FROM NHACUNGCAP ;

/*
 * 2. Mã hàng, tên hàng và số lượng hiện có trong công ty */
SELECT MAHANG , TENHANG ,SOLUONG FROM MATHANG ; 
/* 
 * 3.Địa chỉ, số điện thoại của nhà cung cấp có tên giao dịch VINAMILK là gì?*/
SELECT DIACHI, DIENTHOAI FROM NHACUNGCAP WHERE TENGIAODICH="VINANILK" ;

/* 4. Cho biết mã và tên các mặt hàng có giá lơn hơn 100000 và số lượng hiện có ít hơn 50 */

SELECT MAHANG ,TENHANG FROM MATHANG WHERE GIAHANG >1000 AND SOLUONG <50 ; 

/*
 * 5. Đơn đặt hàng số 1 do ai đặt, do nhân viên nào lập, thời gian và địa điểm giao hàng ở đâu?
 */
SELECT MANHANVIEN ,  NGAYGIAOHANG , NOIGIAOHANG WHERE SOHOADON =1 ;
/*
 * 6.Hiển thị những nhân viên có lương cơ bản cao nhất công ty
 */

SELECT * FROM NHANVIEN WHERE LUONGCOBAN = (SELECT MAX(LUONGCOBAN) FROM NHANVIEN)

/*
 * 7.Nhân viên nào trong công ty bán được nhiều hàng nhất và số lượng bán được là bao nhiêu?
 */
SELECT NHANVIEN.MANHANVIEN , HO , TEN , SUM(SOLUONG) FROM (NHANVIEN INNER JOIN DONDATHANG ON NHANVIEN.MANHANVIEN=DONDATHANG.MANHANVIEN)
INNER JOIN CHITIETDATHANG ON DONDATHANG.SOHOADON=CHITIETDATHANG.SOHOADON
GROUP BY NHANVIEN.MANHANVIEN,HO,TEN, HAVING SUM(SOLUONG)>=ALL(SELECT SUM(SOLUONG) FROM (NHANVIEN INNER JOIN DONDATHANG ON NHANVIEN.MANHANVIEN=DONDATHANG.MANHANVIEN),
INNER JOIN CHITIETDATHANG ON DONDATHANG.SOHOADON=CHITIETDATHANG.SOHOADON,
GROUP BY NHANVIEN.MANHANVIEN,HO,TEN

/* 8. Hãy cho biết tổng sốhàng của mỗi loại hàng */

SELECT MATHANG.MAHANG,TENHANG,MATHANG.SOLUONG + CASE WHEN SUM(CHITIETDATHANG.SOLUONG) IS NULL THEN 0
ELSE SUM(CHITIETDATHANG.SOLUONG) END AS TONGSOLUONG
FROM MATHANG LEFT OUTER JOIN CHITIETDATHANG ON MATHANG.MAHANG=CHITIETDATHANG.MAHANG
GROUP BY MATHANG.MAHANG,TENHANG,MATHANG.SOLUONG

/* 9. Tăng lương lên 50% cho những nhân viên bán được sốlượng hàng >=100 trong năm 2018. */

UPDATE NHANVIEN SET LUONGCOBAN=LUONGCOBAN*0.5 WHERE MANHANVIEN = (SELECT MANHANVIEN FROM DONDATHANG INNER JOIN CHITIETDATHANG ON DONDATHANG.SOHOADON=CHITIETDATHANG.SOHOADON
WHERE MANHANVIEN=NHANVIEN.MANHANVIEN GROUP BY MANHANVIEN HAVING SUM(SOLUONG)>=100)

/* 10. Xóa những đơn hàng có ngày đặt hàng trước năm 2018 ra khỏi CSDL */

DELETE FROM DONDATHANG
WHERE NGAYDATHANG<'1/1/2018'

/* 11.Xóa khỏi bảng NHANVIEN những nhân viên đã làm việc cho công ty trên 20 năm */

DELETE FROM NHANVIEN
WHERE DATEDIFF(YY,NGAYLAMVIEC,GETDATE())>20